=== ImperialAdepts/WebGame/app/Resources/tech-tree.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Resource" type="ResourceType" maxOccurs="unbounded"/>
                <xs:element name="Technology" type="TechnologyType" maxOccurs="unbounded"/>
                <xs:element name="Blueprint" type="BlueprintType" maxOccurs="unbounded"/>
                <xs:element name="UseCase" type="UseCaseType" maxOccurs="unbounded"/>
                <xs:element name="ColonizationPack" type="ColonizationPackType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="ResourceType">
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="unit" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="ResourceRefType">
        <xs:attribute name="ref" type="xs:IDREF"/>
    </xs:complexType>
    <xs:complexType name="ResourcePriceRefType">
        <xs:attribute name="ref" type="xs:IDREF"/>
        <xs:attribute name="count" type="xs:positiveInteger"/>
    </xs:complexType>
    <xs:complexType name="PriceSummaryType">
        <xs:sequence minOccurs="1">
            <xs:element name="Resource" type="ResourcePriceRefType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Product" type="BlueprintProductRefType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="InputRefsType">
        <xs:sequence minOccurs="1">
            <xs:element name="Resource" type="ResourceRefType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Product" type="BlueprintRefType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="TechnologyType">
        <xs:sequence minOccurs="0">
            <xs:element name="inputs" type="InputRefsType"/>
            <xs:element name="usage" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="use" type="UseCaseRefType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
    <xs:complexType name="TechnologyRefType">
        <xs:attribute name="ref" type="xs:IDREF"/>
    </xs:complexType>


    <xs:complexType name="BlueprintType">
        <xs:sequence>
            <xs:element name="Technology" type="TechnologyRefType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="build">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="price" type="PriceSummaryType"/>
                        <xs:element name="constraints" type="PriceSummaryType" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="output" type="xs:IDREF"/>
    </xs:complexType>
    <xs:complexType name="BlueprintRefType">
        <xs:attribute name="ref" type="xs:IDREF"/>
    </xs:complexType>
    <xs:complexType name="BlueprintProductRefType">
        <xs:attribute name="blueprint" type="xs:IDREF"/>
        <xs:attribute name="count" type="xs:positiveInteger"/>
    </xs:complexType>

    <xs:complexType name="UseCaseType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="parent" type="UseCaseRefType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="inputResource" type="ResourceRefType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="inputProduct" type="BlueprintProductRefType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="trait" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="outputResource" type="ResourceRefType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="outputProduct" type="BlueprintProductRefType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
    <xs:complexType name="UseCaseRefType">
        <xs:attribute name="ref" type="xs:IDREF"/>
    </xs:complexType>

    <xs:complexType name="ColonizationPackType">
        <xs:sequence>
            <xs:element name="Resource" type="ResourcePriceRefType" maxOccurs="unbounded"/>
            <xs:element name="Blueprint" type="BlueprintRefType" maxOccurs="unbounded"/>
            <xs:element name="Product" type="BlueprintProductRefType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ImperialAdepts/WebGame/app/Resources/technology-tree.xml
<?xml version="1.0" encoding="utf-8" ?>
<root xmlns:xsd="http://www.w3.org/2001/XMLSchema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="tech-tree.xsd">
    <Resource id="human"/>
    <Resource id="manpower"/>
    <Resource id="stone_block"/>
    <Resource id="iron_ore_deposit"/>
    <Resource id="iron_ore"/>
    <Resource id="land_space"/>
    <Resource id="electricity"/>
    <Technology id="land_building">
        <price>
            <Resource ref="stone_block"/>
            <Resource ref="land_space"/>
        </price>
    </Technology>
    <Technology id="iron_processing">
        <price>
            <Resource ref="iron_ore"/>
            <Resource ref="electricity"/>
        </price>
    </Technology>
    <Blueprint id="settlement_village">
        <build>
            <price>
                <Resource ref="manpower" count="20"/>
            </price>
        </build>
    </Blueprint>
    <Blueprint id="settlement_resource">
        <build>
            <price>
                <Resource ref="manpower" count="20"/>
            </price>
            <constraints>
                <Product blueprint="settlement_village"/>
            </constraints>
        </build>
    </Blueprint>
    <Blueprint id="settlement_laboratory">
        <build>
            <price>
                <Resource ref="manpower" count="20"/>
            </price>
            <constraints>
                <Product blueprint="settlement_village"/>
            </constraints>
        </build>
    </Blueprint>
    <Blueprint id="settlement_farm">
        <build>
            <price>
                <Resource ref="manpower" count="20"/>
            </price>
            <constraints>
                <Product blueprint="settlement_village"/>
            </constraints>
        </build>
    </Blueprint>
    <Blueprint id="basic_iron_mine">
        <Technology ref="iron_processing"/>
        <Technology ref="land_building"/>
        <build>
            <price>
                <Resource ref="iron_ore_deposit" count="10"/>
                <Resource ref="electricity" count="1000"/>
            </price>
            <constraints>
                <Product blueprint="settlement_resource"/>
            </constraints>
        </build>
    </Blueprint>
    <Blueprint id="basic_iron_furnace">
        <Technology ref="iron_processing"/>
        <Technology ref="land_building"/>
        <build>
            <price>
                <Resource ref="iron_ore" count="10"/>
                <Resource ref="electricity" count="1000"/>
            </price>
            <constraints>
                <Product blueprint="settlement_resource"/>
            </constraints>
        </build>
    </Blueprint>
    <ColonizationPack>
        <Resource ref="human" count="1000"/>
        <Blueprint ref="basic_iron_mine"/>
        <Product blueprint="basic_iron_mine" count="1000"/>
    </ColonizationPack>
</root>
